// Exhibition data. Each work is wired to one or more themes; the network view
// draws a line for every work → theme connection.

const THEMES = {
  identity: {
    label: 'IDENTITY',
    blurb: 'Personas, pseudonyms, and selves that only exist because the network does.',
  },
  resistance: {
    label: 'RESISTANCE',
    blurb: 'Infiltrating institutions, juries, and archives to expose who gets left out.',
  },
  bodies: {
    label: 'NETWORKED BODIES',
    blurb: 'Bodies split into frames, scanned, glitched, and reassembled by machines.',
  },
};

const WORKS = [
  {
    id: 'all-new-gen',
    artist: 'VNS Matrix',
    title: 'All New Gen',
    year: '1993–94',
    start: 1993,
    img: 'images/all_new_gen.jpg',
    url: 'https://vnsmatrix.net/projects/all-new-gen',
    themes: ['bodies', 'resistance'],
    text: 'An early cyber-art game originally called "Game Girl." It challenged traditional gender-role notions by following a female/non-binary centric character in a plot that subverted patriarchal narratives. VNS Matrix, the Australian collective behind it, is credited with helping coin the word "cyberfeminism" in 1991.',
  },
  {
    id: 'mouchette',
    artist: 'Martine Neddam',
    title: 'Mouchette',
    year: '1996–ongoing',
    start: 1996,
    img: 'images/mouchette.jpg',
    url: 'https://mouchette.org/',
    themes: ['identity', 'bodies'],
    text: 'Mouchette presents the online persona of a teenage girl, inviting users into unsettling interactions through questions, emails, and choices. The work relies entirely on the internet’s architecture to function.',
    note: 'Touches on self-harm and suicide.',
  },
  {
    id: 'my-boyfriend',
    artist: 'Olia Lialina',
    title: 'My Boyfriend Came Back From the War',
    year: '1996',
    start: 1996,
    img: 'images/lialina.jpg',
    url: 'http://www.teleportacia.org/war/',
    themes: ['identity', 'bodies'],
    text: 'A black-and-white hypertext story of a couple reunited after a war. Each click splits the browser window into smaller frames, so the conversation fractures as you read it and no two readers take the same path. Lialina turns the HTML frameset, a mundane piece of web structure, into the emotional form of the work.',
  },
  {
    id: 'female-extension',
    artist: 'Cornelia Sollfrank',
    title: 'Female Extension',
    year: '1997',
    start: 1997,
    img: 'images/female_extension.jpg',
    url: 'https://artwarez.org/projects/femext/',
    themes: ['identity', 'resistance'],
    text: 'Sollfrank created hundreds of fictitious female artist identities and submitted them to an online jury system, exposing gender bias in digital and institutional networks. The project exists entirely because of internet-based submission processes. When the prizes were announced, all three went to men.',
  },
  {
    id: 'old-boys-network',
    artist: 'Old Boys Network',
    title: 'First Cyberfeminist International',
    year: '1997',
    start: 1997,
    img: 'images/obn.jpg',
    url: 'https://obn.org/',
    themes: ['resistance'],
    text: 'Founded in Berlin in 1997 by artists including Cornelia Sollfrank, Old Boys Network was the first international cyberfeminist alliance. At documenta X in Kassel it convened the First Cyberfeminist International, where participants refused to settle on a single definition and instead wrote the "100 Anti-Theses," a list of everything cyberfeminism is not.',
  },
  {
    id: 'brandon',
    artist: 'Shu Lea Cheang',
    title: 'Brandon',
    year: '1998–99',
    start: 1998,
    img: 'images/brandon.jpg',
    url: 'https://brandon.guggenheim.org/',
    themes: ['identity', 'bodies'],
    text: 'The Guggenheim’s first web-based commission, Brandon unfolded over a year in installments. It starts from the life and 1993 murder of Brandon Teena, a trans man in Nebraska, and builds a multi-author space around gender, the body, surveillance, and punishment. The museum migrated its code in 2017 so it can still be visited today.',
    note: 'Deals with transphobic violence.',
  },
  {
    id: 'subrosa',
    artist: 'subRosa',
    title: 'subRosa',
    year: '1998–ongoing',
    start: 1998,
    img: 'images/subrosa.jpg',
    url: 'http://cyberfeminism.net/',
    themes: ['bodies', 'resistance'],
    text: 'A cyberfeminist art collective co-founded in 1998 by Faith Wilding and Hyla Willis. Through performances, websites, and public workshops, subRosa examines where bodies meet technology and labor: reproductive and genetic technologies, biotech, and the information economy.',
  },
  {
    id: 'she-who-sees',
    artist: 'Morehshin Allahyari',
    title: 'She Who Sees the Unknown',
    year: '2016–21',
    start: 2016,
    img: 'images/allahyari.jpg',
    url: 'https://morehshin.com/she-who-sees-the-unknown/',
    themes: ['bodies', 'resistance'],
    text: 'Allahyari uses 3D modelling, printing, and video to re-figure female and queer jinn and monstrous figures from Middle Eastern myth. Alongside it she developed the idea of "digital colonialism": the way Western institutions and tech companies scan, own, and redistribute the cultural heritage of the Middle East.',
  },
  {
    id: 'glitch-feminism',
    artist: 'Legacy Russell',
    title: 'Glitch Feminism',
    year: '2012–20',
    start: 2012,
    img: 'images/russell.jpg',
    url: 'https://www.legacyrussell.com/',
    themes: ['identity', 'resistance'],
    text: 'First an essay in 2012, then a manifesto published by Verso in 2020. Russell treats the glitch as a refusal: a body that won’t compute inside the gender binary. Online space becomes somewhere queer and Black identities can be rehearsed and built rather than simply observed, carrying cyberfeminism into the age of social media.',
  },
];
